### ISSUE TITLE
CAN wrap struct fields are redundant

### ISSUE THREAD

**Issue by djdupre** [UWCubeSat/DubSat1#112]
Is there a reason we have struct field names like "msp_temp_temp"?

**Comment by jeffchrisope** [comment]
I’m going to blame the CCS renaming “feature”.

**Comment by emorye** [comment]
I found that it was best to not have signals ever share the same names, even if they are exclusively in different packets, since vector displays all of them in one list, and just to avoid confusion. The easiest way to prevent collisions happened to be to preceed the signal name with the frame name. So this is works as intended unless people want me to change it enough.
